CREATE TABLE cars (
  id BIGSERIAL PRIMARY KEY,
  vin VARCHAR(20) NOT NULL,
  year INTEGER NOT NULL,
  make VARCHAR(255) NOT NULL,
  asking_price DECIMAL NOT NULL,
  model VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX cars_vin_index ON cars(vin);